version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}

  nats:
    image: nats:latest
    env_file: ./.env
    ports:
      - ${DEFAULT_NATS_LOCAL_PORT}:${DEFAULT_NATS_DOCKER_PORT}
      - ${CLUSTER_NATS_LOCAL_PORT}:${CLUSTER_NATS_DOCKER_PORT}
      - ${MONITORING_NATS_LOCAL_PORT}:${MONITORING_NATS_DOCKER_PORT}

  app:
    depends_on:
      - mongo
      - nats
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
