version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  spring-boot-app:
    depends_on:
      - mongo
      - nats
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_.HOST=mongo

volumes:
  mongodb:
