name:  Java with Gradle CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3

      - name: Start mongodb
        run: docker run -d --name mongo -p 27017:27017 mongo:latest

      - name: Start nats
        run: docker run -d --name nats -p 4222:4222 nats:latest

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
